### ISSUE TITLE
Internal plugins

### ISSUE THREAD

**Issue by IngwiePhoenix** [aelzenaar/pluma#1]
I'd like to change my app in a way that it utilizes plugins - internal and external. Currently, my initializer looks like so:

```
initThis();
initThat();
initMore();
initOf();
initSuch();
```

... so when I want to add something, I have to update this list. It'd be more convenient to just fire up a manager, get all the plugins, and/or external plugins, initialize them and later delete/unload them.

Is that possible with Pluma? Some plugins may be internal, some not.

**Comment by aelzenaar** [comment]
Hi,

I am not currently involved with the Pluma project (I used to be an on-and-off dev but have not been involved for some time) and so I am not too familiar with the code any more.

This is a mirror of the official sourceforge repo, and I just had a quick look over there - they seem to be reasonably active (a dev commented on an issue there 4 weeks ago), so you might have some luck posting on [their issue tracker](http://sourceforge.net/p/pluma-framework/feature-requests/?source=navbar).

I'm sorry I can't help more, and I hope you get an answer from them that makes sense for what you're trying to do!

**Comment by IngwiePhoenix** [comment]
Ah alright!

Thank you anyway for your reply (: I'll try to post my question there, then.
